// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Infrastructure.DbContexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationService.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20250420181459_NotificationService_Init")]
    partial class NotificationService_Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("NotificationService")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.DataModels.UserNotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("SendToEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("send_to_email");

                    b.Property<bool>("SendToTelegram")
                        .HasColumnType("boolean")
                        .HasColumnName("send_to_telegram");

                    b.Property<bool>("SendToWebsite")
                        .HasColumnType("boolean")
                        .HasColumnName("send_to_website");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_users_notification_settings");

                    b.ToTable("users_notification_settings", "NotificationService");
                });
#pragma warning restore 612, 618
        }
    }
}
