// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetFamily.Discussions.Infrastructure.DbContexts;

#nullable disable

namespace PetFamily.Discussions.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20250426073806_Discussions_Init")]
    partial class Discussions_Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("discussions")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetFamily.Discussions.Domain.Entities.Discussion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("relation_id");

                    b.Property<string>("UserIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("user_ids");

                    b.ComplexProperty<Dictionary<string, object>>("Status", "PetFamily.Discussions.Domain.Entities.Discussion.Status#DiscussionStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");
                        });

                    b.HasKey("Id")
                        .HasName("pk_discussions");

                    b.ToTable("discussions", "discussions");
                });

            modelBuilder.Entity("PetFamily.Discussions.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("discussion_id")
                        .HasColumnType("uuid")
                        .HasColumnName("discussion_id");

                    b.ComplexProperty<Dictionary<string, object>>("IsEdited", "PetFamily.Discussions.Domain.Entities.Message.IsEdited#IsEdited", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Value")
                                .HasColumnType("boolean")
                                .HasColumnName("is_edited");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Text", "PetFamily.Discussions.Domain.Entities.Message.Text#MessageText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(800)
                                .HasColumnType("character varying(800)")
                                .HasColumnName("text");
                        });

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("discussion_id")
                        .HasDatabaseName("ix_messages_discussion_id");

                    b.ToTable("messages", "discussions");
                });

            modelBuilder.Entity("PetFamily.Discussions.Domain.Entities.Message", b =>
                {
                    b.HasOne("PetFamily.Discussions.Domain.Entities.Discussion", null)
                        .WithMany("Messages")
                        .HasForeignKey("discussion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_discussions_discussion_id");
                });

            modelBuilder.Entity("PetFamily.Discussions.Domain.Entities.Discussion", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
