global:
  scrape_interval: 10s
  scrape_timeout: 3s
  
scrape_configs:
  - job_name: "petfamily-scrape"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:5011"] # указываем, что цель находится в нашей сети, а не сети докера
    
  
  