using PetFamily.Application.FilesManagement.FilesData;

namespace PetFamily.Application.FilesManagement.GetPresignedUrl;

public record GetPresignedUrlRequest(GetPresignedUrlData GetPresignedUrlData);