services:
  fileservice:
    container_name: fileservice
    #image: fileservice
    build:
      context: .
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
        NUGET_PASSWORD: ${NUGET_PASSWORD}
      dockerfile: src/FileService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8090:8080"
    networks:
      - shared_network
    restart: always

networks:
  shared_network:
    external: true
