# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: PetFamily.Backend

env:
  NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}
  NUGET_PASSWORD: ${{ secrets.NUGET_PASSWORD }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: |
        dotnet restore ./PetFamily.Backend/Backend/backend.sln
        dotent restore ./PetFamily.Backend/FileService/FileService.sln
        dotnet restore ./PetFamily.Backend/NotificationService/NotificationService.sln
      
    - name: Build
      run: |
        dotnet build ./PetFamily.Backend/Backend/backend.sln --configuration Release --no-restore
        dotent build ./PetFamily.Backend/FileService/FileService.sln --configuration Release --no-restore
        dotnet build ./PetFamily.Backend/NotificationService/NotificationService.sln --configuration Release --no-restore
        
    - name: Tests
      run:  dotnet test ./PetFamily.Backend/Backend/backend.sln --configuration Release --no-restore
